version: '3.9'

services:
  calendar-db:
    image: postgres:16-alpine
    container_name: calendar-db
    ports:
      - "6543:6432"
    environment:
      - POSTGRES_DB=cnrprod1722936513-team-74171
      - POSTGRES_USER=cnrprod1722936513-team-74171
      - POSTGRES_PASSWORD=zoo8taiZou4siid8zaimai0eiChi6uuK

  calendar:
    image: git.codenrock.com:5050/neo-hack-2024-1232/cnrprod1722936513-team-74171/razrabotka-rabochego-instrumenta-dlya-sinhronizacii-ekspertov-rekrutyorov-i-kandidatov-5883
    container_name: calendar
    ports:
      - "60606:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=ci
      - SPRING_DATASOURCE_URL=jdbc:postgresql://rc1b-wwbzmz7xcyzdmat1.mdb.yandexcloud.net:6432/cnrprod1722936513-team-74171
      - POSTGRES_USER=cnrprod1722936513-team-74171
      - POSTGRES_PASSWORD=zoo8taiZou4siid8zaimai0eiChi6uuK