spring:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/calendar
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        ddl-auto: none
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

logging:
  level:
    org:
      zalando:
        logbook: TRACE
      springframework:
        orm:
          jpa: info
          JpaTransactionManager: debug
        transaction: info
        web:
          servlet:
            DispatcherServlet: debug
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
    web: info
