DROP TABLE IF EXISTS users, calendar, meetings, requests, meeting_participant;

CREATE TABLE IF NOT EXISTS users (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name   VARCHAR(50) NOT NULL,
    first_name  VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    email       VARCHAR(512) NOT NULL,
    role        VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS calendar (
    date        DATE PRIMARY KEY,
    type        VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS meetings (
    meeting_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    date         DATE REFERENCES calendar(date),
    start_time   TIME,
    end_time     TIME,
    initiator_id BIGINT REFERENCES users(user_id),
    description  VARCHAR(7000),
    status       VARCHAR(50),
    url          VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id     BIGINT REFERENCES meetings(meeting_id),
    initiator_id   BIGINT REFERENCES users(user_id),
    participant_id BIGINT REFERENCES users(user_id),
    status         VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS meeting_participant (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id     BIGINT REFERENCES meetings(meeting_id),
    participant_id BIGINT REFERENCES users(user_id)
);

INSERT INTO calendar (date, type)
SELECT d,
       CASE
           WHEN EXTRACT(ISODOW FROM d) IN (6, 7) THEN 'HOLIDAY'
           ELSE 'WORKDAY'
           END AS type
FROM generate_series('2024-01-01'::date, '2024-12-31'::date, '1 day'::interval) AS d;

INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Васильев', 'Федор', 'Федорович', 'fedorov33@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Морозов', 'Иван', 'Артемович', 'morozov@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Исков', 'Егор', 'Владимирович', 'isakov@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Третьяков', 'Олег', 'Владимирович', 'tretyakov@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Иванова', 'Ольга', 'МИхайловна', 'ivanova@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Кудрин', 'Петр', 'Иванович', 'kudrin@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Кацапова', 'Светлана', 'Алексеевна', 'katsapova@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Чиркова', 'Марина', 'Александровна', 'chirkova@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Кирова', 'Мария', 'Александровна', 'kirova@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Овчинников', 'Илья', 'Федорович', 'ovchinnikov@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Захаров', 'Илья', 'Федорович', 'zakharov@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Петров', 'Иван', 'Артемович', 'petrov@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Ильясов', 'Егор', 'Владимирович', 'iliyasov@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Архипов', 'Иван', 'Евгеньевич', 'arkhipov@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Трофимова', 'Ольга', 'Михайловна', 'trofimova@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Сухов', 'Петр', 'Алексеевич', 'sukhov@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Друзь', 'Ольга', 'Алексеевна', 'druz@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Ким', 'Мария', 'Александровна', 'kim@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Игнатов', 'Николай', 'Александрович', 'ignatov@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Овчинников', 'Илья', 'Федорович', 'ovchinnikov@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Пушкин', 'Алекснадр', 'Сергеевич', 'pushkin@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Толстой', 'Лев', 'Николаевич', 'tolstoi@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Курина', 'Анастасия', 'Валерьевна', 'kurina@mail.ru', 'RECRUITER');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Веселов', 'Иван', 'Евгеньевич', 'veselov@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Коновалова', 'Ольга', 'Михайловна', 'konovalova@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Муцина', 'Наталья', 'Алексеевна', 'mutsina@mail.ru', 'EXPERT');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Леонтович', 'Дарья', 'Вадимовна', 'leontovich@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Гребенникова', 'Екатерина', 'Александровна', 'grebennikova@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Загородников', 'Владистлав', 'Александрович', 'zagorodnikov@mail.ru', 'CANDIDATE');
INSERT INTO users (last_name, first_name, middle_name, email, role) VALUES ('Томашевсикй', 'Дмитрий', 'Владимирович', 'tomashev@mail.ru', 'RECRUITER');


INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-10', '10:00:00', '11:00:00', 1, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting1');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-11', '11:00:00', '12:00:00', 1, 'собеседование с аналитиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting2');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-12', '12:00:00', '13:00:00', 1, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting3');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-13', '14:00:00', '15:00:00', 2, 'собеседование с разработчиком', 'CONFIRMED', 'https://example.com/meeting4');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-15', '13:00:00', '14:00:00', 2, 'собеседование с аналитиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting5');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-16', '11:00:00', '12:00:00', 2, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting6');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-17', '09:00:00', '10:00:00', 3, 'собеседование с разработчиком', 'CONFIRMED', 'https://example.com/meeting7');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-06', '15:00:00', '16:00:00', 3, 'собеседование с аналитиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting8');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-06', '16:00:00', '17:00:00', 3, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting9');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-15', '16:00:00', '17:00:00', 10, 'собеседование с разработчиком', 'CONFIRMED', 'https://example.com/meeting0');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-15', '09:00:00', '10:00:00', 10, 'собеседование с DE', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting11');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-10', '10:00:00', '11:00:00', 10, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting22');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-11', '11:00:00', '12:00:00', 11, 'собеседование с DE', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting33');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-12', '13:00:00', '14:00:00', 11, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting44');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-13', '15:00:00', '16:00:00', 11, 'собеседование с DE', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting55');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-15', '17:00:00', '18:00:00', 12, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting66');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-16', '09:00:00', '10:00:00', 12, 'собеседование с DE', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting77');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-17', '10:00:00', '11:00:00', 12, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting88');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-07', '12:00:00', '13:00:00', 1, 'собеседование с аналитиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting99');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-07', '14:00:00', '15:00:00', 1, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting00');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-05', '16:00:00', '17:00:00', 1, 'собеседование с аналитиком', 'TOOK_PLACE', 'https://example.com/meeting12');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-05', '11:00:00', '12:00:00', 20, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting123');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-06', '09:00:00', '10:00:00', 20, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting111');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-06', '10:00:00', '11:00:00', 20, 'собеседование с аналитиком', 'TOOK_PLACE', 'https://example.com/meeting222');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-06-14', '12:00:00', '13:00:00', 21, 'собеседование с разработчиком', 'NOT_HAPPENED', 'https://example.com/meeting333');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-18', '14:00:00', '15:00:00', 21, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting444');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-07-19', '16:00:00', '17:00:00', 21, 'собеседование с аналитиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting555');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-05', '10:00:00', '11:00:00', 22, 'собеседование с разработчиком', 'NOT_HAPPENED', 'https://example.com/meeting666');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-08', '12:00:00', '13:00:00', 22, 'собеседование с разработчиком', 'PARTICIPATION_REQUESTED', 'https://example.com/meeting777');
INSERT INTO meetings (title, date, start_time, end_time, initiator_id, description, status, url) VALUES ('собеседование', '2024-08-05', '14:00:00', '15:00:00', 22, 'собеседование с аналитиком', 'NOT_HAPPENED', 'https://example.com/meeting888');


INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (2, 2, 5, 'CONFIRMED');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (2, 2, 5, 'CONFIRMED');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (3, 3, 6, 'PENDING');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (4, 4, 7, 'CONFIRMED');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (5, 1, 8, 'PENDING');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (6, 3, 9, 'PENDING');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (7, 10, 4, 'CONFIRMED');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (8, 11, 4, 'PENDING');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (9, 12, 5, ' REJECTED');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (10, 10, 6, 'PENDING');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (11, 1, 17, 'PENDING');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (12, 1, 18, 'CANCELED');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (13, 2, 19, 'PENDING');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (14, 3, 24, 'CANCELED');
INSERT INTO requests (meeting_id, initiator_id, participant_id, status) VALUES (15, 1, 25, 'PENDING');


INSERT INTO meeting_participant (meeting_id, participant_id) VALUES (1, 1);
INSERT INTO meeting_participant (meeting_id, participant_id) VALUES (2, 1);
INSERT INTO meeting_participant (meeting_id, participant_id) VALUES (3, 1);
INSERT INTO meeting_participant (meeting_id, participant_id) VALUES (4, 2);
INSERT INTO meeting_participant (meeting_id, participant_id) VALUES (5, 2);

